spring.application.name=MyPhamBE
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/thietbididong?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phuongtuong1508@gmail.com
spring.mail.password=pnwrwlvzfbsvcwuy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
#spring.mail.properties.mail.smtp.starttls.required=true
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh

#pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#return-url: http://localhost:8080/api/payment/vnpay-return
#tmn-code: JGV9MSIF
#secret-key: E9QLQ1W7KCLQKQLE5522R5JNRR7WIV8I

vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#vnpay.return-url=http://10.0.2.2/api/vnpayment/return
#vnpay.return-url= "http://10.0.2.2:8080/api/vnpayment/return";
vnpay.return-url=http://10.0.2.2:8080/api/payment/vnpay-return
#vnpay.return-url=http://localhost:8080/api/payment/vnpay-return
#vnpay.return-url=myapp://payment-result
vnpay.tmn-code=JGV9MSIF
vnpay.secret-key=E9QLQ1W7KCLQKQLE5522R5JNRR7WIV8I

#gemini.api.key=AIzaSyDOOMzm2qoFhvqdCPHnc_bfZ3Z4Au193q8
## C?u hình Google Gemini API Key
#spring.ai.google.genai.api-key=AIzaSyBvThIQuRFatswAaIrmDlKiNksQ13yOarU
#
## C?u hình Model và các thông s? AI
#spring.ai.google.genai.chat.options.model=gemini-2.5-flash
#spring.ai.google.genai.chat.options.temperature=0.7
gemini.api.key=AIzaSyD_YQR9Muf4lZXgZi_u87MS80KJCrcACRY
