### 1. Lấy danh sách sản phẩm (GET)
GET http://localhost:8080/api/products/1
Accept: application/json
### 1. Lấy danh sách sản phẩm (GET)
GET http://localhost:8080/api/reviews/product/1
Accept: application/json
### 2. Gửi tin nhắn cho AI (POST)
POST http://localhost:8080/api/chat/send
Content-Type: application/json

{
  "message": "Shop còn kem chống nắng không?"
}

### 3. Đăng nhập để lấy Token (Ví dụ)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

### 4. Test API cần quyền Admin (Dùng Token)
GET http://localhost:8080/api/admin/orders
Authorization: Bearer {{auth_token}}

### 🔥 LẤY DANH SÁCH ORDER (KHÔNG TOKEN)
GET http://localhost:8080/api/orders/user/1
Content-Type: application/json


### 🔥 LẤY DANH SÁCH ORDER (CÓ TOKEN)
GET http://localhost:8080/api/orders/user/10
Content-Type: application/json
Authorization: Bearer YOUR_TOKEN_HERE


### 🔥 TẠO ORDER
POST http://localhost:8080/api/orders/create/1
Content-Type: application/json
Authorization: Bearer YOUR_TOKEN_HERE

[
  {
    "productId": 1,
    "quantity": 2
  },
  {
    "productId": 2,
    "quantity": 1
  }
]
### 3. Lấy chi tiết đơn hàng
GET http://127.0.0.1:8080/api/orders/10

---

### 4. Hủy đơn hàng (Chuyển status thành CANCELLED)
PUT http://127.0.0.1:8080/api/orders/1/cancel

---

### 5. Mua lại đơn hàng
POST http://127.0.0.1:8080/api/orders/1/reorder


GET http://localhost:8080/api/admin/products
Accept: application/json
### Lấy thống kê Dashboard
GET http://localhost:8080/api/categories
Accept: application/json

